### ISSUE TITLE
Could you please tell me where the 'train_coco/annotations_HSI.json' file is located? I couldn't find it in the processed folder.

### ISSUE THREAD

**Issue by zly1213811** [jonggyujang0123/M2SODAI#3]

**Comment by zly1213811** [comment]
Sorry, I made a mistake. After carefully reviewing the code, I solved the problem by loading the original .json file.

**Comment by jonggyujang0123** [comment]
Thank you very much for your interest in our code.

We have found an issue with the code during our replication process. Using the current version may not yield the expected results. We are actively addressing this problem, so we kindly ask for your patience.
