### ISSUE TITLE
How long will it take for the “Prepare Dataset” to be released?

### ISSUE THREAD

**Issue by guoying918** [jonggyujang0123/M2SODAI#4]

**Comment by jonggyujang0123** [comment]
Thank you for your interest in our work.
First of all, sorry for our lateness.

A good news is that the dataset will be released mid-april.

**Comment by guoying918** [comment]
Thanks for the quick reply and your excellent work and contribution. 

Looking forward to your dataset.

**Comment by jonggyujang0123** [comment]
Please reopen this issue if you need more help regarding this.
